describe('Login Test', () => {
    it('Visits the Login Page', () => {
      cy.visit('localhost:3000')
      cy.get('input[name="email"]').should('be.visible')
      cy.get('input[name="password"]').should('be.visible')
      cy.contains('Continue').should('be.visible')
    })
    it('Should validate invalid inputs',() => {
        cy.contains('Continue').click()
        cy.contains('Email Address cannot be empty').should('be.visible')
        cy.contains('Password cannot be empty').should('be.visible')
        cy.get('input[name="email"]').type("abcd")
        cy.get('input[name="password"]').type("abcd")
        cy.contains('Continue').click()
        cy.contains('Please enter a valid email').should('be.visible')
        cy.contains('Password should be over 8 characters long').should('be.visible')
    })
    it('Should check if email exists in database', () => {
        cy.get('input[name="email"]').type("abcd@gmail.com")
        cy.get('input[name="password"]').type("Password1")
        cy.contains('Continue').click()
        cy.contains('User with email doesn\'t exist').should('be.visible')
    })
    it('Should check email/password combination', () => {
        cy.get('input[name="email"]').clear()
        cy.get('input[name="password"]').clear()
        cy.get('input[name="email"]').type("Admin@gmail.com")
        cy.get('input[name="password"]').type("Password1")
        cy.contains('Continue').click()
        cy.contains('Invalid Email/Password Combination').should('be.visible')
    })
    it('Should redirect upon successful login', () => {
        cy.get('input[name="email"]').clear()
        cy.get('input[name="password"]').clear()
        cy.get('input[name="email"]').type("Admin@gmail.com")
        cy.get('input[name="password"]').type("Password12@")
        cy.contains('Continue').click()
        cy.url().should('include', '/dashboard')
        cy.contains('Logged in successfully').should('be.visible')
    })
  })
