/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import ReplaceAlphanumericString from '../../utils/ReplaceAlphanumericString'
import Bin from './Bin'

type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh
    Cube001: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube014: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube021: THREE.Mesh
    Cube002: THREE.Mesh
    Cube004: THREE.Mesh
    Cube026: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Cube040: THREE.Mesh
    Cube049: THREE.Mesh
    Cube052: THREE.Mesh
    Cube072: THREE.Mesh
    Cube003: THREE.Mesh
    Cube005: THREE.Mesh
    Cube017: THREE.Mesh
    Cube041: THREE.Mesh
    Cube042: THREE.Mesh
    Cube043: THREE.Mesh
    Cube044: THREE.Mesh
    Cube045: THREE.Mesh
    Cube046: THREE.Mesh
    Cube047: THREE.Mesh
    Cube048: THREE.Mesh
    Cube050: THREE.Mesh
    Cube051: THREE.Mesh
    Cube053: THREE.Mesh
    Cube054: THREE.Mesh
    Cube057: THREE.Mesh
    Cube067: THREE.Mesh
    Cube069: THREE.Mesh
    Cube070: THREE.Mesh
    Cube071: THREE.Mesh
    Cube073: THREE.Mesh
    Cube074: THREE.Mesh
    Cube075: THREE.Mesh
    Cube076: THREE.Mesh
    Cube077: THREE.Mesh
    Cube078: THREE.Mesh
    Cube079: THREE.Mesh
    Cube080: THREE.Mesh
    Cube081: THREE.Mesh
    Cube082: THREE.Mesh
    Cube083: THREE.Mesh
    Cube084: THREE.Mesh
    Cube085: THREE.Mesh
    Cube086: THREE.Mesh
    Cube087: THREE.Mesh
    Cube088: THREE.Mesh
    Cube089: THREE.Mesh
    Cube090: THREE.Mesh
    Cube091: THREE.Mesh
    Cube092: THREE.Mesh
    Cube093: THREE.Mesh
    Cube094: THREE.Mesh
    Cube095: THREE.Mesh
    Cube096: THREE.Mesh
    Cube098: THREE.Mesh
    Cube099: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube027: THREE.Mesh
    Cube055: THREE.Mesh
    Cube056: THREE.Mesh
    Cube058: THREE.Mesh
    Cube059: THREE.Mesh
    Cube060: THREE.Mesh
    Cube061: THREE.Mesh
    Cube062: THREE.Mesh
    Cube063: THREE.Mesh
    Cube064: THREE.Mesh
    Cube065: THREE.Mesh
    Cube066: THREE.Mesh
    Cube068: THREE.Mesh
    Cube097: THREE.Mesh
    Cube100: THREE.Mesh
    Cube102: THREE.Mesh
    Cube103: THREE.Mesh
    Cube104: THREE.Mesh
    Cube105: THREE.Mesh
    Cube106: THREE.Mesh
    Cube107: THREE.Mesh
    Cube108: THREE.Mesh
  }
  materials: {
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.069']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.062']: THREE.MeshStandardMaterial
    ['Material.072']: THREE.MeshStandardMaterial
    ['Material.065']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.071']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.058']: THREE.MeshStandardMaterial
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.060']: THREE.MeshStandardMaterial
    ['Material.063']: THREE.MeshStandardMaterial
    ['Material.064']: THREE.MeshStandardMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    ['Material.067']: THREE.MeshStandardMaterial
    ['Material.068']: THREE.MeshStandardMaterial
    ['Material.070']: THREE.MeshStandardMaterial
    ['Material.047']: THREE.MeshStandardMaterial
    ['Material.048']: THREE.MeshStandardMaterial
    ['Material.050']: THREE.MeshStandardMaterial
    ['Material.051']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    ['wood.002']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.045']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['wood.003']: THREE.MeshStandardMaterial
    ['Material.057']: THREE.MeshStandardMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.056']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.074']: THREE.MeshStandardMaterial
    ['Material.075']: THREE.MeshStandardMaterial
  }
}

interface ModelProps {
  areatag: string;
  racktag: string;
  position: [x: number, y: number, z: number];
  changeposition?: (num: [x: number, y: number, z: number]) => void;
  currentbintags?: string[]
}


const Model: React.FC<ModelProps> = ({
  areatag,
  racktag,
  position,
  changeposition,
  currentbintags
}) =>  {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/finalrack.glb') as GLTFResult

  const CreateBoxes = () => {
    const initialx = -1.5;
    const initialy = -10.5;
    const boxarray = [];
    for (let i = 0; i < 11; i += 1) {
      for (let j = 0; j < 4; j += 1) {
        boxarray.push(
          <Bin
            position={[initialx + j * 5, initialy + i * 2, 8]}
            currentbintags={currentbintags}
            areatag={areatag}
            racktag={racktag}
            leveltag={ReplaceAlphanumericString("L01", i)}
            sectiontag={ReplaceAlphanumericString("S01", j)}
          />
        );
      }
    }
    return boxarray;
  };

  
  return (
    <group ref={group} dispose={null} position={position}
    onClick={() => changeposition(position)}>
      {CreateBoxes()}
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.026']} position={[-7.5, 0.5, -2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.040']} position={[2.5, -6, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.043']} position={[2.5, -10, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.042']} position={[2.5, -8, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.039']} position={[2.5, -4, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.035']} position={[2.5, 0, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.029']} position={[2.5, 6, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.037']} position={[2.5, -2, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.069']} position={[-7.5, -4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.032']} position={[2.5, 8, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.059']} position={[-7.5, 8.03, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.062']} position={[-7.5, 4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.072']} position={[-7.5, -8, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.065']} position={[-7.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.034']} position={[2.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[2.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[2.5, 10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[2.5, -2, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[2.5, 8, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[2.5, 6, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube031.geometry} material={nodes.Cube031.material} position={[2.5, 4, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} position={[2.5, 2, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} position={[2.5, 0, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube034.geometry} material={nodes.Cube034.material} position={[2.5, -4, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[2.5, -8, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} position={[2.5, -10, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.024']} position={[2.5, 0.5, -2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.023']} position={[-7.5, 0.5, 2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} position={[2.5, -6, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Material.011']} position={[-2.5, 0.5, 2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube049.geometry} material={nodes.Cube049.material} position={[-2.5, -8, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['Material.071']} position={[-7.5, -8, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube072.geometry} material={materials['Material.025']} position={[-2.5, 0.5, -2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-2.5, 8, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-2.5, 6, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[-2.5, 4, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube041.geometry} material={nodes.Cube041.material} position={[-2.5, 2, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube042.geometry} material={nodes.Cube042.material} position={[-2.5, 0, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube043.geometry} material={nodes.Cube043.material} position={[-2.5, -2, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} position={[-2.5, -4, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} position={[-2.5, -6, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Material.028']} position={[2.5, 8.03, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube047.geometry} material={nodes.Cube047.material} position={[2.5, 4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[2.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube050.geometry} material={materials['Material.038']} position={[2.5, -4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['Material.041']} position={[2.5, -8, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials['Material.022']} position={[2.5, 0.5, 2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[2.5, 0.5, -2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials['Material.027']} position={[2.5, 10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube067.geometry} material={materials['Material.073']} position={[-7.5, -10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube069.geometry} material={nodes.Cube069.material} position={[2.5, 8.03, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube070.geometry} material={materials['Material.030']} position={[2.5, 4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube071.geometry} material={nodes.Cube071.material} position={[-2.5, 10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube073.geometry} material={materials['Material.058']} position={[-7.5, 10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube074.geometry} material={materials['Material.061']} position={[-7.5, 8, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube075.geometry} material={materials['Material.060']} position={[-7.5, 6, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube076.geometry} material={materials['Material.063']} position={[-7.5, 4, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube077.geometry} material={materials['Material.064']} position={[-7.5, 2, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube078.geometry} material={materials['Material.066']} position={[-7.5, 0, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube079.geometry} material={materials['Material.067']} position={[-7.5, -2, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube080.geometry} material={materials['Material.068']} position={[-7.5, -4, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube081.geometry} material={materials['Material.070']} position={[-7.5, -6, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube082.geometry} material={materials['Material.047']} position={[-2.5, 8.03, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube083.geometry} material={materials['Material.048']} position={[-2.5, 4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube084.geometry} material={materials['Material.050']} position={[-2.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube085.geometry} material={materials['Material.051']} position={[-2.5, -4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube086.geometry} material={materials['Material.055']} position={[-2.5, -8, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube087.geometry} material={materials.wood} position={[-2.5, -10, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube088.geometry} material={materials.wood} position={[-2.5, 10, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube089.geometry} material={materials.wood} position={[-2.5, 8, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube090.geometry} material={materials.wood} position={[-2.5, 6, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube091.geometry} material={materials.wood} position={[-2.5, 4, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube092.geometry} material={materials.wood} position={[-2.5, 2, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube093.geometry} material={materials.wood} position={[-2.5, 0, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube094.geometry} material={materials.wood} position={[-2.5, -2, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube095.geometry} material={materials.wood} position={[-2.5, -4, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube096.geometry} material={materials.wood} position={[-2.5, -6, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube098.geometry} material={nodes.Cube098.material} position={[-2.5, -10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube099.geometry} material={materials.wood} position={[-2.5, -8, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-2.5, 4, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['wood.002']} position={[-2.5, -4, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.031']} position={[2.5, 4, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.033']} position={[2.5, 2, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.046']} position={[-2.5, 4, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.045']} position={[-2.5, 8, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.044']} position={[-2.5, 10, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube055.geometry} material={materials['Material.049']} position={[-2.5, 0, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube056.geometry} material={materials['Material.054']} position={[-2.5, -6, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials['Material.036']} position={[-2.5, 2, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials['wood.003']} position={[-2.5, 2, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube060.geometry} material={materials['Material.057']} position={[-2.5, -10, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube061.geometry} material={materials['Material.052']} position={[-2.5, -2, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials['Material.017']} position={[-2.5, -2, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube063.geometry} material={materials['Material.053']} position={[-2.5, -4, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube064.geometry} material={materials['Material.056']} position={[-2.5, -8, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube065.geometry} material={materials['Material.010']} position={[-2.5, 10, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube066.geometry} material={materials['Material.012']} position={[-2.5, 8, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube068.geometry} material={materials['Material.013']} position={[-2.5, 6, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube097.geometry} material={materials['Material.014']} position={[-2.5, 4, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube100.geometry} material={materials['Material.015']} position={[-2.5, 2, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube102.geometry} material={nodes.Cube102.material} position={[-2.5, -2, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube103.geometry} material={materials['Material.018']} position={[-2.5, -4, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube104.geometry} material={materials['Material.019']} position={[-2.5, -6, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube105.geometry} material={materials['Material.020']} position={[-2.5, -8, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube106.geometry} material={materials['Material.021']} position={[-2.5, -10, 2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube107.geometry} material={materials['Material.074']} position={[-2.5, 6, -2]} scale={[5, 0.15, 0.15]} />
      <mesh geometry={nodes.Cube108.geometry} material={materials['Material.075']} position={[-2.5, 0, 2]} scale={[5, 0.15, 0.15]} />
    </group>
  )
}

useGLTF.preload('/finalrack.glb')
export default Model;