/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube016: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

interface ModelProps {
  id: number;
  initialX: number;
  initialY: number;
  initialZ: number;
}

const Model: React.FC = () => {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/binsgrouped.glb") as GLTFResult;
  return (
    <group ref={group} dispose={null}>
      <group position={[0.37, 5.94, -0.98]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight
          intensity={1000}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[1.81, 0.97, 0.04]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[1.81, 1.91, 0.03]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[1.81, 2.82, 0.03]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-0.21, 0.98, 0.05]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-0.24, 1.88, 0]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-2.22, 1.88, 0.03]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-2.23, 0.95, 0.01]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-2.24, 2.8, 0.03]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-0.21, 2.82, 0.01]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[-2.24, 0.06, 0]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-0.2, 0.05, 0.04]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[-2.24, -0.84, 0.03]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-0.22, -0.83, 0.07]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[1.87, 0.06, 0.01]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[1.82, -0.91, 0.03]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[-0.22, -1.78, 0.03]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[-2.24, -1.76, 0.01]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[1.8, -1.82, 0.03]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[-2.21, -2.66, 0.01]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[-0.21, -2.66, 0.02]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[1.81, -2.65, 0.04]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.Material}
        position={[-2.21, -3.12, 0.05]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[1.81, 0.92, 0.07]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[-0.21, 0.93, 0.08]}
        scale={[0.85, 0.29, 0.51]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[-2.23, 0.01, 0.04]}
        scale={[0.85, 0.29, 0.51]}
      />
    </group>
  );
};
export default Model;

useGLTF.preload("/binsgrouped.glb");
