/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SM_Office_Door_Door_0: THREE.Mesh
    SM_Office_Door_Doorway_0: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_2004: THREE.Mesh
    Object_3004: THREE.Mesh
    Object_4004: THREE.Mesh
    Cylinder_Material001_0: THREE.Mesh
    wall_fan_spin1_wall_fan_shader_0: THREE.Mesh
    defaultMaterial: THREE.Mesh
    Cube_0001: THREE.Mesh
    Cube_0014: THREE.Mesh
    Cube_0016: THREE.Mesh
    Cylinder_Material001_0006: THREE.Mesh
    Cylinder_Material001_0007: THREE.Mesh
    Cylinder_Material001_0008: THREE.Mesh
    SM_Office_Door_Door_0001: THREE.Mesh
    SM_Office_Door_Doorway_0001: THREE.Mesh
    Cube_0030: THREE.Mesh
    Cube_0031: THREE.Mesh
    Cube_0032: THREE.Mesh
    Cube_0034: THREE.Mesh
    Cube_0035: THREE.Mesh
    Cube_0036: THREE.Mesh
    Cube_0037: THREE.Mesh
    Cube_0039: THREE.Mesh
    Cube_0040: THREE.Mesh
    Cube_0041: THREE.Mesh
    Cube_0042: THREE.Mesh
    Cube_0043: THREE.Mesh
    Cube_0044: THREE.Mesh
    Cube_0046: THREE.Mesh
    Cube_0047: THREE.Mesh
    Cube_0048: THREE.Mesh
    Cube_0050: THREE.Mesh
    Cube_0051: THREE.Mesh
    Cube_0052: THREE.Mesh
    Cube_0053: THREE.Mesh
    Cube_0054: THREE.Mesh
    Cube_0055: THREE.Mesh
    Cube_0056: THREE.Mesh
    Cube_0058: THREE.Mesh
    Cube_0059: THREE.Mesh
    Cube_0033: THREE.Mesh
    Cube_0060: THREE.Mesh
    Cube006: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube054: THREE.Mesh
    Cube056: THREE.Mesh
    Cube057: THREE.Mesh
    Cube207: THREE.Mesh
    Cube207_1: THREE.Mesh
    Cube216: THREE.Mesh
    Cube216_1: THREE.Mesh
    Cube219: THREE.Mesh
    Cube219_1: THREE.Mesh
    Cube008: THREE.Mesh
    Cube: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube234: THREE.Mesh
    Cube234_1: THREE.Mesh
    Cube235: THREE.Mesh
    Cube235_1: THREE.Mesh
    Cube236: THREE.Mesh
    Cube236_1: THREE.Mesh
    Cube007: THREE.Mesh
    Cube009: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube241: THREE.Mesh
    Cube241_1: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube025: THREE.Mesh
    Cube032: THREE.Mesh
    Cube049: THREE.Mesh
    Cube050: THREE.Mesh
    Cube051: THREE.Mesh
    Cube089: THREE.Mesh
    Cube090: THREE.Mesh
  }
  materials: {
    Door: THREE.MeshStandardMaterial
    Doorway: THREE.MeshStandardMaterial
    ['5_-_Default']: THREE.MeshStandardMaterial
    Material_57: THREE.MeshStandardMaterial
    standard_alumini: THREE.MeshStandardMaterial
    Material_46: THREE.MeshStandardMaterial
    ['2_-_Default']: THREE.MeshStandardMaterial
    ['3_-_Default']: THREE.MeshStandardMaterial
    ['material_0.004']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    wall_fan_shader: THREE.MeshStandardMaterial
    extincteur: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Door.001']: THREE.MeshStandardMaterial
    ['Doorway.001']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Material.056']: THREE.MeshStandardMaterial
    ['Material.058']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.060']: THREE.MeshStandardMaterial
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.063']: THREE.MeshStandardMaterial
    ['Material.064']: THREE.MeshStandardMaterial
    ['Material.065']: THREE.MeshStandardMaterial
    ['Material.072']: THREE.MeshStandardMaterial
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.074']: THREE.MeshStandardMaterial
    ['Material.076']: THREE.MeshStandardMaterial
    ['Material.077']: THREE.MeshStandardMaterial
    ['Material.078']: THREE.MeshStandardMaterial
    ['Material.080']: THREE.MeshStandardMaterial
    ['Material.081']: THREE.MeshStandardMaterial
    ['Material.082']: THREE.MeshStandardMaterial
    ['Material.083']: THREE.MeshStandardMaterial
    ['Material.084']: THREE.MeshStandardMaterial
    ['Material.085']: THREE.MeshStandardMaterial
    ['Material.086']: THREE.MeshStandardMaterial
    ['Material.088']: THREE.MeshStandardMaterial
    ['Material.089']: THREE.MeshStandardMaterial
    ['Material.090']: THREE.MeshStandardMaterial
    ['Material.092']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
  }
}

interface ModelProps {
  position: [x: number, y: number, z: number];
}


const Model: React.FC<ModelProps> = ({position}) => {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/office.glb') as GLTFResult
  return (
    <group ref={group} dispose={null} position={position}>
      <group position={[6, -0.57, 50]} rotation={[-Math.PI / 2, 0, 0]} scale={2.63}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[24, 0.43, 54]} rotation={[-Math.PI / 2, 0, -3.14]} scale={0.06}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.SM_Office_Door_Door_0.geometry} material={materials.Door} position={[11.48, 3.38, -11.26]} />
            <mesh geometry={nodes.SM_Office_Door_Doorway_0.geometry} material={materials.Doorway} position={[12.66, -0.04, -7.7]} />
          </group>
        </group>
      </group>
      <group position={[-2, 6.43, 59]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.09, 0.11, 0.09]}>
        <group position={[33.86, 0.91, 40.49]}>
          <group position={[-33.86, -0.91, -40.49]}>
            <mesh geometry={nodes.Object_16.geometry} material={materials['5_-_Default']} position={[0, 0, -1.92]} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Material_57} position={[-0.05, -0.12, -1.42]} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.standard_alumini} position={[0, 0, -1.56]} />
          </group>
        </group>
        <group position={[-21.04, 0.02, 38.46]}>
          <group position={[21.04, -0.02, -38.46]}>
            <mesh geometry={nodes.Object_11.geometry} material={materials['5_-_Default']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.standard_alumini} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Material_46} />
          </group>
          <group position={[21.04, 0.8, -0.31]}>
            <group position={[0, -0.83, -38.16]}>
              <mesh geometry={nodes.Object_8.geometry} material={materials['2_-_Default']} />
              <mesh geometry={nodes.Object_9.geometry} material={materials['3_-_Default']} />
            </group>
          </group>
        </group>
        <group position={[100.52, 292.34, -3.87]} />
      </group>
      <group position={[-5, 2.43, 50]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8}>
        <group position={[-5.69, -6.22, 6.25]} rotation={[-0.27, 0.6, 1.93]} />
        <group position={[2.71, 3.57, -5.48]} rotation={[-2.26, 0.75, -1.96]} />
      </group>
      <group position={[-31, 1.43, 52]} rotation={[-Math.PI, 0, 0]} scale={[2.46, 2.46, 3.58]} />
      <group position={[3, 6.43, 61]} rotation={[-1.86, 0.06, -0.46]} scale={0.01}>
        <mesh geometry={nodes.Object_2004.geometry} material={materials['material_0.004']} />
        <mesh geometry={nodes.Object_3004.geometry} material={materials['material_0.004']} />
        <mesh geometry={nodes.Object_4004.geometry} material={materials['material_0.004']} />
      </group>
      <group position={[7, 5.43, 61]} rotation={[-Math.PI / 2, 0, 0]} scale={2.83} />
      <group position={[8, 7.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[247.77, -37.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.022']} />
          </group>
        </group>
      </group>
      <group position={[7, 0.43, 68]} rotation={[-Math.PI / 2, 0, -2.13]} scale={0.06} />
      <group position={[-36, 0.43, 119]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.wall_fan_spin1_wall_fan_shader_0.geometry} material={materials.wall_fan_shader} position={[313.04, 76.19, -458.73]} rotation={[Math.PI, 0, -0.48]} scale={-0.3} />
        </group>
      </group>
      <group position={[-14, 9.43, 69]} rotation={[-Math.PI / 2, 0, 0]} scale={2.68}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-5, 2.43, 70]} rotation={[-Math.PI / 2, 0, 0]} scale={2.64}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.extincteur} position={[-2.54, 1.53, -10.58]} scale={0.71} />
        </group>
      </group>
      <group position={[-5, 2.43, 50]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8}>
        <mesh geometry={nodes.Cube_0001.geometry} material={materials['Material.001']} position={[-3.43, -9.58, 0.56]} rotation={[0, 0, 1.57]} scale={[1.59, 1.35, 1.66]} />
      </group>
      <group position={[-5, 2.43, 50]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-11, 0.43, 53]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-22, 0.43, 53]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-16, 2.43, 50]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-42, 1.43, 50]} rotation={[-Math.PI, 0, 0]} scale={[2.46, 2.46, 3.58]} />
      <group position={[-23, 0.43, 67]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-16, 2.43, 64]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-42, 1.43, 64]} rotation={[-Math.PI, 0, 0]} scale={[2.46, 2.46, 3.58]} />
      <group position={[-11, 0.43, 67]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-5, 2.43, 64]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-31, 1.43, 64]} rotation={[-Math.PI, 0, 0]} scale={[2.46, 2.46, 3.58]} />
      <group position={[-8, 0.43, 67]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-8, 0.43, 67]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-8, 0.43, 67]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-8, 0.43, 70]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-8, 2.43, 67]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8}>
        <mesh geometry={nodes.Cube_0014.geometry} material={materials['Material.018']} position={[-1.5, 3.12, 2.28]} rotation={[0, 0, 1.2]} scale={[0.55, 0.34, 0.34]} />
      </group>
      <group position={[-8, 0.43, 67]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-9, 2.43, 56]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8}>
        <mesh geometry={nodes.Cube_0016.geometry} material={materials['Material.020']} position={[-1.79, 3.12, 2.08]} rotation={[0, 0, 1.57]} scale={[0.55, 0.34, 0.34]} />
      </group>
      <group position={[11, 7.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[10, 4.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[7, 4.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[1, 4.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[4, 4.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[7, 2.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[247.77, -37.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder_Material001_0006.geometry} material={materials['Material.028']} position={[0, 0, -0.62]} scale={[1, 1, 1.13]} />
          </group>
        </group>
      </group>
      <group position={[10, 2.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[247.77, -37.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder_Material001_0007.geometry} material={materials['Material.029']} position={[0, 0, -0.62]} scale={[1, 1, 1.13]} />
          </group>
        </group>
      </group>
      <group position={[4, 2.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[247.77, -37.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder_Material001_0008.geometry} material={materials['Material.030']} position={[0, 0, -0.62]} scale={[1, 1, 1.13]} />
          </group>
        </group>
      </group>
      <group position={[1, 2.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-10, 2.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-7, 2.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2, 2.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-4, 2.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-7, 4.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-10, 4.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-4, 4.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2, 4.43, 60]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-68, 0.43, 28]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-68, 0.43, 26]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-68, 0.43, 28]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-68, 0.43, 28]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-68, 0.43, 28]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-45, 1.43, 30]} rotation={[0, 0.04, -Math.PI]} scale={[2.46, 2.46, 3.58]} />
      <group position={[-70, 2.43, 31]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-64, 0.43, 28]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-34, 1.43, 30]} rotation={[0, 0.04, -Math.PI]} scale={[2.46, 2.46, 3.58]} />
      <group position={[-59, 2.43, 31]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-53, 0.43, 28]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-33, 1.43, 44]} rotation={[0, 0.04, -Math.PI]} scale={[2.46, 2.46, 3.58]} />
      <group position={[-59, 2.43, 45]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-53, 0.43, 41]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-64, 0.43, 42]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-70, 2.43, 45]} rotation={[-Math.PI / 2, 0, -3.1]} scale={1.8} />
      <group position={[-45, 1.43, 42]} rotation={[0, 0.04, -Math.PI]} scale={[2.46, 2.46, 3.58]} />
      <group position={[-11, 0.43, 34]} rotation={[Math.PI / 2, 0, -3.14]} scale={-0.06}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.SM_Office_Door_Door_0001.geometry} material={materials['Door.001']} position={[-26.75, 13.5, -7.02]} rotation={[0, 0, -0.71]} />
            <mesh geometry={nodes.SM_Office_Door_Doorway_0001.geometry} material={materials['Doorway.001']} position={[0, 0, -7.02]} />
          </group>
        </group>
      </group>
      <group position={[-11, -0.57, 56]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0030.geometry} material={materials['Material.054']} position={[-1.14, 4.08, 2.59]} rotation={[0, 0, 1.57]} scale={[0.55, 0.52, 0.4]} />
      </group>
      <group position={[-10, -0.57, 58]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0031.geometry} material={materials['Material.055']} position={[-1.37, 3.98, 2.59]} rotation={[0, 0, 1.57]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[-10, -0.57, 63]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0032.geometry} material={materials['Material.056']} position={[-1.37, 4.55, 2.59]} rotation={[0, 0, 1.64]} scale={[0.99, 0.48, 0.4]} />
      </group>
      <group position={[-11, -0.57, 61]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.05, 1.8, 1.8]} />
      <group position={[-10, -0.57, 68]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0034.geometry} material={materials['Material.058']} position={[-1.37, 3.87, 2.34]} rotation={[0, 0, 1.73]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[-11, -0.57, 66]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0035.geometry} material={materials['Material.059']} position={[-1.14, 4.57, 2.75]} rotation={[0, 0, 1.49]} scale={[0.18, 0.52, 0.4]} />
      </group>
      <group position={[-11, -2.57, 66]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0036.geometry} material={materials['Material.060']} position={[-1.14, 4.08, 2.19]} rotation={[0, 0, 1.71]} scale={[0.55, 0.52, 0.4]} />
      </group>
      <group position={[-10, -2.57, 68]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0037.geometry} material={materials['Material.061']} position={[-1.37, 3.98, 2.19]} rotation={[0, 0, 1.57]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[-11, -2.57, 61]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.05, 1.8, 1.8]} />
      <group position={[-10, -2.57, 63]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0039.geometry} material={materials['Material.063']} position={[-1.37, 4.49, 2]} rotation={[0, 0, 1.66]} scale={[1.06, 0.48, 0.21]} />
      </group>
      <group position={[-10, -2.57, 58]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0040.geometry} material={materials['Material.064']} position={[-1.37, 3.98, 2.19]} rotation={[0, 0, 1.57]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[-11, -2.57, 56]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0041.geometry} material={materials['Material.065']} position={[-1.14, 4.08, 2.19]} rotation={[0, 0, 1.57]} scale={[0.55, 0.52, 0.4]} />
      </group>
      <group position={[25, -2.57, 58]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0042.geometry} material={materials['Material.072']} position={[-1.37, 3.98, 2.19]} rotation={[0, 0, 1.66]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[23, -2.57, 58]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0043.geometry} material={materials['Material.073']} position={[-1.14, 4.08, 2.19]} rotation={[0, 0, 1.51]} scale={[0.55, 0.52, 0.4]} />
      </group>
      <group position={[30, -2.57, 58]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0044.geometry} material={materials['Material.074']} position={[-1.37, 3.98, 2.19]} rotation={[0, 0, 1.57]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[27, -2.57, 58]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[2.05, 1.8, 1.8]} />
      <group position={[27, -0.57, 58]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0046.geometry} material={materials['Material.076']} position={[-1.14, 4.08, 2.74]} rotation={[0, 0, 1.49]} scale={[0.55, 0.52, 0.4]} />
      </group>
      <group position={[30, -0.57, 58]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0047.geometry} material={materials['Material.077']} position={[-1.37, 3.87, 2.77]} rotation={[0, 0, 1.73]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[23, -0.57, 58]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0048.geometry} material={materials['Material.078']} position={[-1.14, 4.08, 2.75]} rotation={[0, 0, 1.63]} scale={[0.55, 0.52, 0.4]} />
      </group>
      <group position={[25, -0.57, 58]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[2.24, 1.8, 1.8]} />
      <group position={[3, -2.57, 58]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0050.geometry} material={materials['Material.080']} position={[-1.37, 5.47, 2.19]} rotation={[0, 0, 1.66]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[0, -2.57, 58]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0051.geometry} material={materials['Material.081']} position={[-1.14, 5.57, 2.19]} rotation={[0, 0, 1.51]} scale={[0.55, 0.52, 0.4]} />
      </group>
      <group position={[7, -2.57, 58]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0052.geometry} material={materials['Material.082']} position={[-1.37, 5.47, 2.19]} rotation={[0, 0, 1.57]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[5, -2.57, 58]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0053.geometry} material={materials['Material.083']} position={[-1.14, 5.57, 2.1]} rotation={[0, 0, 1.71]} scale={[0.42, 0.4, 0.31]} />
      </group>
      <group position={[5, -0.57, 58]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0054.geometry} material={materials['Material.084']} position={[-1.14, 5.57, 2.66]} rotation={[1.56, 0, 1.51]} scale={[0.35, 0.52, 0.4]} />
      </group>
      <group position={[7, -0.57, 58]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[2.24, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0055.geometry} material={materials['Material.085']} position={[-1.37, 5.36, 2.8]} rotation={[0, 0, 1.73]} scale={[0.55, 0.48, 0.4]} />
      </group>
      <group position={[0, -0.57, 58]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0056.geometry} material={materials['Material.086']} position={[-1.14, 5.57, 2.34]} rotation={[0, 0, 1.63]} scale={[0.55, 0.52, 0.4]} />
      </group>
      <group position={[3, -0.57, 58]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[2.24, 1.8, 1.8]} />
      <group position={[3, -0.57, 66]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8}>
        <mesh geometry={nodes.Cube_0058.geometry} material={materials['Material.088']} position={[-1.5, 3.12, 2.54]} rotation={[0, 0, 1.57]} scale={[0.36, 0.22, 0.22]} />
      </group>
      <group position={[3, -2.57, 66]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8}>
        <mesh geometry={nodes.Cube_0059.geometry} material={materials['Material.089']} position={[-1.5, 3.12, 2.13]} rotation={[0, 0, 1.57]} scale={[0.55, 0.34, 0.34]} />
      </group>
      <group position={[-11, -0.57, 67]} rotation={[-Math.PI / 2, 0, 0.04]} scale={[2.05, 1.8, 1.8]}>
        <mesh geometry={nodes.Cube_0033.geometry} material={materials['Material.090']} position={[-1.14, 4.57, 2.75]} rotation={[0, 0, 1.49]} scale={[0.18, 0.52, 0.4]} />
      </group>
      <group position={[-9, 2.43, 59]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8} />
      <group position={[-9, 2.43, 63]} rotation={[-Math.PI / 2, 0, 0]} scale={1.8}>
        <mesh geometry={nodes.Cube_0060.geometry} material={materials['Material.092']} position={[2.39, 1.08, 1.96]} rotation={[0, 0, 1.49]} scale={[-0.85, -1.38, -0.16]} />
      </group>
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.007']} position={[-15, 3.43, 63]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.17, 2.62, 0.15]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.007']} position={[-15, 3.43, 53]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.17, 2.62, 0.15]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.007']} position={[-11, 3.43, 63]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.17, 2.62, 0.15]} />
      <mesh geometry={nodes.Cube054.geometry} material={materials['Material.007']} position={[-11, 3.43, 52]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.17, 2.62, 0.15]} />
      <mesh geometry={nodes.Cube056.geometry} material={materials['Material.007']} position={[-15, 3.43, 47]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.17, 2.65, 0.15]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials['Material.007']} position={[-11, 3.43, 47]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.17, 2.65, 0.15]} />
      <group position={[-13, 0.43, 55]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[7.85, 0.22, 2.14]}>
        <mesh geometry={nodes.Cube207.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube207_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-13, 5.43, 55]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[7.85, 0.22, 2.14]}>
        <mesh geometry={nodes.Cube216.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube216_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-13, 3.43, 55]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[7.85, 0.22, 2.14]}>
        <mesh geometry={nodes.Cube219.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube219_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-5, 0.43, 50]} rotation={[0, 0, Math.PI / 2]} scale={0.1} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[7, 7.46, 53]} scale={[17.59, 7.65, 5.69]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.007']} position={[24, 3.43, 59]} rotation={[0, 0.01, 0]} scale={[0.23, 2.65, 0.15]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.007']} position={[24, 3.43, 62]} rotation={[0, 0.01, 0]} scale={[0.23, 2.65, 0.15]} />
      <group position={[7, 0.43, 60]} rotation={[0, 0.01, 0]} scale={[17.69, 0.23, 2.24]}>
        <mesh geometry={nodes.Cube234.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube234_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[7, 5.43, 60]} rotation={[0, 0.01, 0]} scale={[17.69, 0.23, 2.24]}>
        <mesh geometry={nodes.Cube235.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube235_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[7, 3.43, 60]} rotation={[0, 0.01, 0]} scale={[17.69, 0.23, 2.24]}>
        <mesh geometry={nodes.Cube236.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube236_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.007']} position={[14, 5.43, 59]} rotation={[0, 0.01, 0]} scale={[0.14, 5.42, 0.15]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.007']} position={[14, 5.43, 63]} rotation={[0, 0.01, 0]} scale={[0.14, 5.42, 0.15]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.007']} position={[3, 5.43, 63]} rotation={[0, 0.01, 0]} scale={[0.14, 5.42, 0.15]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.007']} position={[3, 5.43, 59]} rotation={[0, 0.01, 0]} scale={[0.14, 5.42, 0.15]} />
      <group position={[8, 11.43, 61]} rotation={[0, 0.01, 0]} scale={[5.6, 0.23, 2.12]}>
        <mesh geometry={nodes.Cube241.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube241_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.007']} position={[-11, 3.43, 59]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={[0.17, 2.57, 0.15]} />
      <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[-5, 0.43, 50]} rotation={[-Math.PI, 1.57, -Math.PI]} scale={0.1} />
      <mesh geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[-28, 1.43, 55]} rotation={[3.06, 0, 3.08]} scale={0.1} />
      <mesh geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} position={[-15, 3.43, 69]} rotation={[-Math.PI / 2, 0, 1.57]} scale={0.1} />
      <mesh geometry={nodes.Cube049.geometry} material={materials['Material.053']} position={[7, 12.43, 30.58]} scale={[17.59, 12.63, 16.73]} />
      <mesh geometry={nodes.Cube050.geometry} material={nodes.Cube050.material} position={[-5, 0.43, 50]} rotation={[-Math.PI / 2, 0, -2.44]} scale={0.1} />
      <mesh geometry={nodes.Cube051.geometry} material={nodes.Cube051.material} position={[19, 0.43, 30]} rotation={[Math.PI / 2, 0, -2.44]} scale={-0.1} />
      <mesh geometry={nodes.Cube089.geometry} material={nodes.Cube089.material} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Cube090.geometry} material={nodes.Cube090.material} rotation={[0, 0.04, 0]} />
    </group>
  )
}

useGLTF.preload('/office.glb')
export default Model;