/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh
    Cube001: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube014: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube021: THREE.Mesh
    Cube002: THREE.Mesh
    Cube004: THREE.Mesh
    Cube026: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Cube040: THREE.Mesh
    Cube049: THREE.Mesh
    Cube052: THREE.Mesh
    Cube072: THREE.Mesh
    Cube003: THREE.Mesh
    Cube005: THREE.Mesh
    Cube041: THREE.Mesh
    Cube042: THREE.Mesh
    Cube043: THREE.Mesh
    Cube044: THREE.Mesh
    Cube045: THREE.Mesh
    Cube046: THREE.Mesh
    Cube047: THREE.Mesh
    Cube048: THREE.Mesh
    Cube050: THREE.Mesh
    Cube051: THREE.Mesh
    Cube053: THREE.Mesh
    Cube054: THREE.Mesh
    Cube055: THREE.Mesh
    Cube058: THREE.Mesh
    Cube068: THREE.Mesh
    Cube070: THREE.Mesh
    Cube071: THREE.Mesh
    Cube073: THREE.Mesh
    Cube074: THREE.Mesh
    Cube075: THREE.Mesh
    Cube076: THREE.Mesh
    Cube077: THREE.Mesh
    Cube078: THREE.Mesh
    Cube079: THREE.Mesh
    Cube080: THREE.Mesh
    Cube081: THREE.Mesh
    Cube082: THREE.Mesh
    Cube083: THREE.Mesh
    Cube084: THREE.Mesh
    Cube085: THREE.Mesh
    Cube086: THREE.Mesh
    Cube087: THREE.Mesh
    Cube088: THREE.Mesh
    Cube089: THREE.Mesh
    Cube090: THREE.Mesh
    Cube091: THREE.Mesh
    Cube092: THREE.Mesh
    Cube093: THREE.Mesh
    Cube094: THREE.Mesh
    Cube095: THREE.Mesh
    Cube096: THREE.Mesh
    Cube097: THREE.Mesh
    Cube099: THREE.Mesh
    Cube100: THREE.Mesh
  }
  materials: {}
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/smallrack.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-7.5, 0.5, -2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[2.5, -6, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[2.5, -10, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[2.5, -8, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[2.5, -4, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[2.5, 0, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[2.5, 2, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[2.5, 4, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[2.5, 6, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[2.5, -2, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[-7.5, -4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[2.5, 8, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[-7.5, 8.03, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[-7.5, 4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[-7.5, -8, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[-7.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[2.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[2.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[2.5, 10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[2.5, -2, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[2.5, 8, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[2.5, 6, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube031.geometry} material={nodes.Cube031.material} position={[2.5, 4, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} position={[2.5, 2, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} position={[2.5, 0, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube034.geometry} material={nodes.Cube034.material} position={[2.5, -4, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[2.5, -8, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} position={[2.5, -10, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube037.geometry} material={nodes.Cube037.material} position={[2.5, 0.5, -2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[-7.5, 0.5, 2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} position={[2.5, -6, 0.01]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube040.geometry} material={nodes.Cube040.material} position={[-2.5, 0.5, 2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube049.geometry} material={nodes.Cube049.material} position={[-2.5, -8, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube052.geometry} material={nodes.Cube052.material} position={[-7.5, -8, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube072.geometry} material={nodes.Cube072.material} position={[-2.5, 0.5, -2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-2.5, 8, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-2.5, 6, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube041.geometry} material={nodes.Cube041.material} position={[-2.5, 4, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube042.geometry} material={nodes.Cube042.material} position={[-2.5, 2, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube043.geometry} material={nodes.Cube043.material} position={[-2.5, 0, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} position={[-2.5, -2, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} position={[-2.5, -4, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube046.geometry} material={nodes.Cube046.material} position={[-2.5, -6, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube047.geometry} material={nodes.Cube047.material} position={[2.5, 8.03, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[2.5, 4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube050.geometry} material={nodes.Cube050.material} position={[2.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube051.geometry} material={nodes.Cube051.material} position={[2.5, -4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube053.geometry} material={nodes.Cube053.material} position={[2.5, -8, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[2.5, 0.5, 2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} position={[2.5, 0.5, -2]} scale={[0.15, 11.5, 0.15]} />
      <mesh geometry={nodes.Cube058.geometry} material={nodes.Cube058.material} position={[2.5, 10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube068.geometry} material={nodes.Cube068.material} position={[-7.5, -10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube070.geometry} material={nodes.Cube070.material} position={[2.5, 8.03, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube071.geometry} material={nodes.Cube071.material} position={[2.5, 4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube073.geometry} material={nodes.Cube073.material} position={[-2.5, 10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube074.geometry} material={nodes.Cube074.material} position={[-7.5, 10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube075.geometry} material={nodes.Cube075.material} position={[-7.5, 8, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube076.geometry} material={nodes.Cube076.material} position={[-7.5, 6, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube077.geometry} material={nodes.Cube077.material} position={[-7.5, 4, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube078.geometry} material={nodes.Cube078.material} position={[-7.5, 2, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube079.geometry} material={nodes.Cube079.material} position={[-7.5, 0, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube080.geometry} material={nodes.Cube080.material} position={[-7.5, -2, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube081.geometry} material={nodes.Cube081.material} position={[-7.5, -4, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube082.geometry} material={nodes.Cube082.material} position={[-7.5, -6, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube083.geometry} material={nodes.Cube083.material} position={[-2.5, 8.03, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube084.geometry} material={nodes.Cube084.material} position={[-2.5, 4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube085.geometry} material={nodes.Cube085.material} position={[-2.5, 0, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube086.geometry} material={nodes.Cube086.material} position={[-2.5, -4, 0.05]} rotation={[2.36, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube087.geometry} material={nodes.Cube087.material} position={[-2.5, -8, 0.05]} rotation={[Math.PI / 4, 0, 0]} scale={[0.21, 0.2, 2.8]} />
      <mesh geometry={nodes.Cube088.geometry} material={nodes.Cube088.material} position={[-2.5, -10, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube089.geometry} material={nodes.Cube089.material} position={[-2.5, 10, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube090.geometry} material={nodes.Cube090.material} position={[-2.5, 8, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube091.geometry} material={nodes.Cube091.material} position={[-2.5, 6, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube092.geometry} material={nodes.Cube092.material} position={[-2.5, 4, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube093.geometry} material={nodes.Cube093.material} position={[-2.5, 2, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube094.geometry} material={nodes.Cube094.material} position={[-2.5, 0, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube095.geometry} material={nodes.Cube095.material} position={[-2.5, -2, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube096.geometry} material={nodes.Cube096.material} position={[-2.5, -4, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube097.geometry} material={nodes.Cube097.material} position={[-2.5, -6, 0]} scale={[5, 0.19, 2]} />
      <mesh geometry={nodes.Cube099.geometry} material={nodes.Cube099.material} position={[-2.5, -10, -0.04]} scale={[0.16, 0.14, 2]} />
      <mesh geometry={nodes.Cube100.geometry} material={nodes.Cube100.material} position={[-2.5, -8, 0]} scale={[5, 0.19, 2]} />
    </group>
  )
}

useGLTF.preload('/smallrack.glb')
